/** @format */

export const oderActionTypes = {
	ADD_ITEM_TO_ODER_LIST: 'ADD_ITEM_TO_ODER_LIST',
	DELETE_ITEM_FROM_ODER_LIST: 'DELETE_ITEM_FROM_ODER_LIST',
	REMOVE_MESSAGE: 'REMOVE_MESSAGE',
	SET_MESSAGE: 'SET_MESSAGE',
	TOGGLE_IS_ACTIVE: 'TOGGLE_IS_ACTIVE',
	FOCUS_IS_SALE_PANEL: 'FOCUS_IS_SALE_PANEL',
};

// export default oderActionTypes;
